[[items]]
title = "<a href=\"/when/#teacher-s-program\">Proposal submissions</a> for the Teacher's Program opened"
date = "Jan 23, 2024"

[[items]]
title = '<a href="/who/#volunteers">Volunteer application</a> opened'
date = "Jan 21, 2024"

[[items]]
title = "Website officially launched"
date = "Jan 21, 2024"
